apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploytest
  name: deploytest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploytest
  template:
    metadata:
      labels:
        app: deploytest
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: Recreate
