apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-deploy
  name: mealie-deploy
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie-deploy
  clusterIP: 10.43.252.37
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.249
